// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnd7EQeOmUofDymcBfmMq8qtp9Zx3aVMI',
    appId: '1:971160597593:web:48bcda3355b638bc326d48',
    messagingSenderId: '971160597593',
    projectId: 'hua-chat-app',
    authDomain: 'hua-chat-app.firebaseapp.com',
    storageBucket: 'hua-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAocW3-H9UFHUBvdzmrmkhN93ESxTUxiCA',
    appId: '1:971160597593:android:323c253ee61ed16c326d48',
    messagingSenderId: '971160597593',
    projectId: 'hua-chat-app',
    storageBucket: 'hua-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARE7LOpyBBT1isE3delwPuxkk-p0Bf5sk',
    appId: '1:971160597593:ios:f97fd87c90d983cc326d48',
    messagingSenderId: '971160597593',
    projectId: 'hua-chat-app',
    storageBucket: 'hua-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.hua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARE7LOpyBBT1isE3delwPuxkk-p0Bf5sk',
    appId: '1:971160597593:ios:f97fd87c90d983cc326d48',
    messagingSenderId: '971160597593',
    projectId: 'hua-chat-app',
    storageBucket: 'hua-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.hua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnd7EQeOmUofDymcBfmMq8qtp9Zx3aVMI',
    appId: '1:971160597593:web:146c0ab9805a1557326d48',
    messagingSenderId: '971160597593',
    projectId: 'hua-chat-app',
    authDomain: 'hua-chat-app.firebaseapp.com',
    storageBucket: 'hua-chat-app.firebasestorage.app',
  );
}
